// Generated by https://quicktype.io

import { InternalAPIResponseProps } from './responses';

export type LeaderboardResponseProps = InternalAPIResponseProps<LeaderboardData>;

export type LeaderboardData = Record<string, Pup[]>;

export interface Pup {
  wallet: string;
  id: string;
  dps: number;
}
